server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081
    fetch-registry: true
    register-with-eureka: true

spring:
    application:
      name: mircroservices
    jpa:
      show-sql: false
      hibernate:
          ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    jmx:
      enabled: false
    datasource:
      url: jdbc:postgresql://localhost:5432/dev_microservices
      username: postgres
      password: postgres
